@startuml
!include ../../style.puml

skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

class LogicManager
class "<<interface>>\nLogic" as Logic
Class "{abstract}\nCommand" as Command
Class XYZCommand
package "Parser" as ParserPackage{}
}


package Model {}
package Storage {}


Class " " as HiddenSource #FFFFFF
skinparam classBorderColor White


HiddenSource .down.> Logic
LogicManager .right-|> Logic
LogicManager -down->ParserPackage
LogicManager ..> Command: <<execute>>
ParserPackage .down.> XYZCommand: <<create>>
XYZCommand -up-|> Command



Command .left> Model
LogicManager --> Model
LogicManager -left> Storage


Model --up[hidden] Storage

hide member

@enduml