@startuml
!include ../../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class ApplicationParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMap
Class ArgumentTokenizer
Class Flag

}

Package "Validator classes" as ValidatorPackage{
Class "<<interface>>\nValidator" as Validator
Class ApplicationStatusValidator
Class CompanyNameValidator
Class JobApplicationIndexValidator
Class JobTitleValidator

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> ApplicationParser
hide HiddenOutside

'Parser Dependencies
ApplicationParser .down.> XYZCommandParser: <<create>>
XYZCommandParser ..> XYZCommand : <<create>>
ApplicationParser ..> Command : <<use>>
XYZCommandParser -up-|> Parser
XYZCommandParser ..> ArgumentMap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Flag
CliSyntax .[hidden] ParserUtil
XYZCommandParser ..> ParserUtil
ParserUtil .down..> Validator
ArgumentTokenizer .down.> Flag
XYZCommand -up-|> Command

'Validator Dependencies
ApplicationStatusValidator -right-|> Validator
CompanyNameValidator -up-|> Validator
JobApplicationIndexValidator -up-|> Validator
JobTitleValidator -left-|> Validator

hide member

@enduml