@startuml
!include ../../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR_T4
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

class StorageManager
class "<<interface>>\nStorage" as Storage
Class "ApplicationSerializer" as ApplicationSerializer
Class "HashUtil" as HashUtil
}


package Model {}

Class " " as HiddenSource #FFFFFF
skinparam classBorderColor White

HiddenSource .down.> Storage
StorageManager .up-|> Storage
StorageManager .left.> HashUtil: <<hashes>>
StorageManager  .right.> ApplicationSerializer: <<serializes>>
ApplicationSerializer .down-> Model
StorageManager ..> Model



hide member


@enduml