@startuml

interface Storage {
    readApplicationsFromFile(): ArrayList<InternshipApplication>
    storeApplicationsToFile(applications: InternshipApplication[]): void
}

class StorageManager implements Storage {
    readApplicationsFromFile(): ArrayList<InternshipApplication>
    storeApplicationsToFile(applications: InternshipApplication[]): void
}

@enduml