@startuml

skinparam ClassAttributeIconSize 0
skinparam classBackgroundColor green
skinparam classBorderColor black
skinparam classArrowColor darkgreen
skinparam classFontColor white
hide circle

package Model {
    class ApplicationManager
}

package UI as UiPackage {
    class UiMain {
        - ui : UiMain
        - scan : Scanner

        + UiMain()
        + getInstance()
        + readInput() : String
        + introMessage()
        + helpOutput()
        + printApplications()
        + handleError()
        + showLineBreak()
        + exitMessage()
    }
    class UiTable {
        <u> + getTable() : String
        <u> - getColumnWidths() : int[]
        <u> - getHorizontalBorder() : String
        <u> - getRow() : String
        <u> - getCell() : String

    }
    class UiConstants {
        <u> + INTRO_MESSAGE : String
        <u> + HELP_MESSAGE : String
        <u> + LOGO : String
        <u> + TABLE_HEADER_ARRAYLIST : ArrayList<String>
        <u> + LINE_BREAK : String
    }
}

ApplicationManager << (X,#FFFFFF) >>
ApplicationManager --> UiMain : getInstance()

UiMain ..> UiTable
UiMain ..> UiConstants

@enduml
