@startuml


skinparam ClassAttributeIconSize 0
skinparam classBackgroundColor UI_COLOR




package UI as UiPackage {
    class UiMain {
        - ui : UiMain
        - scan : Scanner

        + UiMain()
        + getInstance()
    }
    class UiTable {
        <u> + getTable() : String
    }
    class UiConstants {
        <u> + TABLE_HEADER_ARRAYLIST : ArrayList<String>
    }
}

Class " " as HiddenSource #FFFFFF
skinparam classBorderColor White
HiddenSource "1"-[UI_COLOR]-> UiMain

UiMain .[UI_COLOR].> UiTable
UiMain .[UI_COLOR].> UiConstants

@enduml
