@startuml
!include ../../style.puml

actor user as user USER_COLOR
participant ":UI" as ui UI_COLOR
participant ":Logic" as logic LOGIC_COLOR
participant ":Model" as model MODEL_COLOR
participant ":Storage" as storage STORAGE_COLOR

user -> ui: "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic: parseCommand("delete 1")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model: delete internship application from list
activate model MODEL_COLOR
model -[MODEL_COLOR]->logic
deactivate model

logic -[LOGIC_COLOR]> storage: saveState(applicationList)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage
deactivate storage

storage -[STORAGE_COLOR]-> logic
deactivate storage

logic -[LOGIC_COLOR]-> ui
deactivate logic

ui -[UI_COLOR]-> user
deactivate ui

@enduml