@startuml

!include ../../style.puml

participant LogJob #grey

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ApplicationParser" as ApplicationParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "a:ListCommand" as ListCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ApplicationManager" as ApplicationManager MODEL_COLOR
end box

box UI UI_COLOR_T1
participant ":UI" as ui UI_COLOR
end box

LogJob -> LogicManager : execute(...)
activate LogicManager

LogicManager -> ApplicationParser: parseCommand(args)
activate ApplicationParser

create ListCommandParser
ApplicationParser -> ListCommandParser
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand
activate ListCommand
ListCommand --> ListCommandParser
deactivate

ListCommandParser --> ApplicationParser
deactivate ListCommandParser
ApplicationParser -> LogicManager
destroy ListCommandParser
deactivate ApplicationParser

LogicManager -> ListCommand: execute()
activate ListCommand
ListCommand -> ApplicationManager: list(application)
activate ApplicationManager
ApplicationManager --> ListCommand: observableList
deactivate ApplicationManager
ListCommand --> LogicManager: commandResult
deactivate ListCommand
destroy ListCommand

LogicManager -> ui: printMessage(listSuccess)
activate ui
ui --> LogicManager
deactivate ui
deactivate ListCommand
LogicManager --> LogJob

@enduml